name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    uses: artkrsk/stub-package-workflows/.github/workflows/stub-test.yml@80bc95942e895c60c3cfb9c92fd657c6a663dbce # master
    with:
      stub_file: wpml-stubs.php
