name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: artkrsk/stub-package-workflows/.github/workflows/stub-release.yml@master
    with:
      release_title: 'WPML'
